### PR TITLE
Fix product cannot be added to wishlist on website assigned to custom stock

### LINKED ISSUE #3018: Unable to add product with multi-source inventory to wishlist with
### Preconditions (*)

1. Magento Commerce 2.3.4, vanilla 

### Steps to reproduce (*)

1. Create a new inventory source -named 'new-source'-  in the Magento Admin
2. Create a new stock inventory -named 'new-stock'- the Magento Admin, assign 'new-source' and default website to the 'new-stock'. Ensure that the setup is similar to:
Screenshot 2020-04-04 at 23 40 40
3. Create a simple product and only assign "new-stock" as in inventory:
Screenshot 2020-04-04 at 23 48 56
4. Visit the the simple product product detail page in frontend.
5. Add the product to the wishlist.
6. The following error shows:
Screenshot 2020-04-05 at 00 00 50

### Expected result (*)

1. The product should be added to the wishlist.

### Actual result (*)

1. The product is not added to the wishlist.

### PR DESCRIPTION
**Pull request by bubasuma**
Unable to add product with multi-source inventory to wishlist with

### Description (*)

- Added generic "in-stock" filter for select object in CatalogInventory.
- Added plugin in InventoryCatalog to handle in-stock constraint for custom stock
- Added new module InventoryWishlist for MFTF test coverage of this scenario

The new generic "in-stock" filter can now be used to filter products or any product related entities. As for now, existing filters are restricted to product collections leading to code duplication for other entities. For instance:
\Magento\InventoryCatalog\Model\ResourceModel\AddIsInStockFieldToCollection
\Magento\InventoryCatalog\Model\ResourceModel\AddIsInStockFilterToCollection
\Magento\InventoryCatalog\Plugin\CatalogInventory\Model\Indexer\ModifySelectInProductPriceIndexFilter

### Fixed Issues (if relevant)

1. Fixes magento/inventory#3018: Unable to add product with multi-source inventory to wishlist with

### Manual testing scenarios (*)

1. Create a new inventory source -named 'new-source' in the Magento Admin
2. Create a new stock inventory -named 'new-stock' in the Magento Admin, assign 'new-source' and default website to the 'new-stock'
3. Create a simple product and only assign "new-stock" as in inventory
4. Go to storefront and log in to a customer account
5. Visit the the simple product product detail page in frontend
6. Add the product to the wishlist

ACTUAL 🔴 
The product is not added to the wishlist. The following error message is shown: _We can't add the item to Wish List right now: Cannot add product without stock to wishlist._

EXPECTED 🟢 
- [ ] The product is added to the wishlist and successful message is shown.
- [ ] The product is visible in customer wishlist 

### Related Pull Requests
https://github.com/magento-mpi/magento2ce/pull/526
https://github.com/magento-mpi/magento2-infrastructure/pull/34
https://github.com/magento-commerce/magento2-infrastructure/pull/1307

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by bubasuma** [comment]
I am working on test coverage.

File: InventoryCatalog/Model/ResourceModel/StockStatusFilter.php [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+     * @return Select
+     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
+     */
+    public function execute(
+        Select $select,
+        string $entityTable,
+        string $entityIdField,
+        string $stockStatusTableAlias,
+        int $stockId,
+        bool $force = false
```
Comment (sidolov) [inline InventoryCatalog/Model/ResourceModel/StockStatusFilter.php]: Looks like a hack as for me. Could you please describe use cases for that flag?

File: InventoryCatalog/Model/ResourceModel/StockStatusFilter.php [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+    ): Select {
+        if ($force || !$this->stockConfiguration->isShowOutOfStock()) {
+            $productTableAlias = null;
+            $productTable = $select->getConnection()->getTableName('catalog_product_entity');
+            foreach ($select->getPart(Select::FROM) as $tableAlias => $part) {
```
Comment (sidolov) [inline InventoryCatalog/Model/ResourceModel/StockStatusFilter.php]: It's not a good idea to find table alias this way. Is it possible to pass it from the client code? Or split to the few filters for particular cases instead of implementing a generic one?

**Review by sidolov — CHANGES_REQUESTED** [review]

File: InventoryCatalog/Model/ResourceModel/StockStatusFilter.php [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+
+    /**
+     * Add in-stock status constraint to the select for non default stock
+     *
+     * @param Select $select
+     * @param string $productTableAlias
+     * @param string $stockStatusTableAlias
+     * @param int $stockId
+     * @return Select
+     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
```
Comment (sidolov) [inline InventoryCatalog/Model/ResourceModel/StockStatusFilter.php]: I believe this line is redundant.

**Review by sidolov — APPROVED** [review]

**Review by sidolov — CHANGES_REQUESTED** [review]
Please, fix minor review issue

**Review by sidolov — APPROVED** [review]

**Comment by bubasuma** [comment]
@magento run all tests

**Comment by bubasuma** [comment]
@magento run all tests

**Comment by bubasuma** [comment]
@magento run all tests

**Comment by engcom-Oscar** [comment]
Hi @bubasuma , I have tested this PR and when I add product to wishlist, I didn't have successful message is shown. May you please recheck?

**Comment by bubasuma** [comment]
Hi @engcom-Oscar
I have checked it on 2.4-develop + fix and it works as expected for me. Please see video recording https://www.loom.com/share/794b392475b24f6b8a7233004edabd3c

FYI: You have to be logged in as customer in storefront. (I will update the description)

**Comment by bubasuma** [comment]
@magento run all tests

**Comment by bubasuma** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento import pr to magento-commerce/inventory

**Comment by magento-engcom-team** [comment]
@sidolov the pull request successfully imported.

**Comment by bubasuma** [comment]
@magento run Static Tests
