### PR TITLE
Use of NoSuchEntityException instead of InputException in GetProductI…

### LINKED ISSUE #1275: Substitute  InputException -> NoSuchEntityException in services determining SKU by Id and vice versa
Currently, we have two services 

\Magento\InventoryCatalog\Model\GetProductIdsBySkus
```
        if (!empty($notFoundedSkus)) {
            throw new InputException(
                __('Following products with requested skus were not found: %1', implode($notFoundedSkus, ', '))
            );
        }
```
and 
\Magento\InventoryCatalog\Model\GetSkusByProductIds
```
        if (!empty($notFoundedIds)) {
            throw new InputException(
                __('Following products with requested ids were not found: %1', implode($notFoundedIds, ', '))
            );
        }
```
both of services throw InputException, 
\Magento\Framework\Exception\NoSuchEntityException should be used instead

Also need to make a decision whether we need to throw an exception at all, as we already agreed that Catalog should be decoupled from Inventory

### PR DESCRIPTION
**Pull request by giacmir**
…dsBySkus and GetSkusByProductIds

fixes #1275

### Description
- Substituted InputException with NoSuchEntityException in \Magento\InventoryCatalog\Model\GetProductIdsBySkus and \Magento\InventoryCatalog\Model\GetSkusByProductIds;
- changed PHPDoc in inherited Interfaces;
- updated expected exception in class uses and test. 

### Fixed Issues (if relevant)

1. magento-engcom/msi#1275: Substitute InputException -> NoSuchEntityException in services determining SKU by Id and vice versa #1275 

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=1340) <br/>All committers have signed the CLA.

File: app/code/Magento/InventoryCatalog/Model/GetProductIdsBySkus.php [hunk 1]
```diff
@@ -7,9 +7,9 @@
 
 namespace Magento\InventoryCatalog\Model;
 
-use Magento\InventoryCatalogApi\Model\GetProductIdsBySkusInterface;
 use Magento\Catalog\Model\ResourceModel\Product as ProductResourceModel;
-use Magento\Framework\Exception\InputException;
```
Comment (naydav) [inline app/code/Magento/InventoryCatalog/Model/GetProductIdsBySkus.php:12]: Pls, check `use` declaration in all of changed files

For example `app/code/Magento/InventoryCatalog/Model/SourceItemsSaveSynchronization/SetDataToLegacyCatalogInventory.php` has unused dependency

**Review by naydav — CHANGES_REQUESTED** [review]

**Review by maghamed — APPROVED** [review]
