### PR TITLE
fix: log exceptions during source distance calculation

### LINKED ISSUE #3420: In store pickup silently discards exceptions
Currently, exceptions thrown during the in store pickup source distance calculations are being silently discarded. This PR simply logs the exceptions when they are caught.

### Preconditions (*)
1. Google API as Distance Provider
2. Google API Key with invalid permissions (eg, referrer restrictions applied).

### Steps to reproduce (*)
1. Configure source selection as preconditions
2. Navigate to checkout, and attempt a pick up at store address lookup

### Expected result (*)
1. Error message in logs outlining, when the lookup failed

### Actual result (*)
1. Error logs are empty, requiring a debugger/source changes to identify the failure reason

### PR DESCRIPTION
**Pull request by SamJUK**
Log exceptions encountered during In Stock Pickup source distance calculation instead of silently discarding them.

Fixes: #3420

### CODE REVIEW

**Comment by engcom-Hotel** [comment]
@magento run all tests

File: InventoryInStorePickup/Model/SearchRequest/Area/GetDistanceToSources.php [hunk 1]
```diff
@@ -47,22 +48,30 @@ class GetDistanceToSources
...
      * @param Pipeline $searchTermPipeline
+     * @param Logger $logger
      */
     public function __construct(
         GetLatsLngsFromAddressInterface $getLatsLngsFromAddress,
         GetOrderedDistanceToSources $getOrderedDistanceToSources,
         AddressInterfaceFactory $addressInterfaceFactory,
-        Pipeline $searchTermPipeline
+        Pipeline $searchTermPipeline,
+        LoggerInterface $logger
```
Comment (engcom-Hotel) [inline InventoryInStorePickup/Model/SearchRequest/Area/GetDistanceToSources.php]: $logger should be null by default
```suggestion
        LoggerInterface $logger=null
```

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @SamJUK,

Thanks for the contribution!

Please look into the below review comments. And also check the review comments made by the Copilot.

The failed tests seems flaky to me, will re-run to be double sure.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Integration Tests, Static Tests, Unit Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Review by engcom-Hotel — APPROVED** [review]
Failed tests seems flaky to me, hence approving the PR.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
Hello @SamJUK,

Please find below the QA feedback for this PR:

:heavy_check_mark: QA Passed

**Preconditions:**

1. Google API as Distance Provider
2. Google API Key with invalid permissions (eg, referrer restrictions applied).

**Manual testing scenario:**

1. Configure source selection as preconditions
2. Navigate to checkout, and attempt a pick up at store address lookup

**Actual Result:** :heavy_check_mark:

- Error message in logs outlining, when the lookup failed

**Before**

- Error logs are empty, requiring a debugger/source changes to identify the failure reason

**After**

- Error message in logs outlining, when the lookup failed

Since some automated tests are failing, hence checking this PR further.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
After investigating the B2B functional test failure, I found that the test is flaky.

Known Issues:

- MC-16583: https://jira.corp.adobe.com/browse/ACQE-8517

Flaky Issues:
- B2B-1505

Hence moving forward with this PR.

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B
